version: '3'
services:
  frontend:
    build: ./frontend
    volumes:
      # Frontend source files
      - ./frontend/src:/app/frontend/src
    ports:
      - 8000:8000
  backend:
    build: ./backend
    volumes: 
      # Backend source
      - ./backend:/app
    ports:
      - 8080:8080