version: '3'
services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - 8000:8000
    command: yarn dev
  backend:
    build: ./backend
    volumes: 
      - ./backend:/app/backend
    ports:
      - 8080:8080
    command: go run main.go